version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Run Unit Tests
          command: |
            pytest > result.log || true

      - run:
          name: Run Dependency Check
          command: |
            pip install safety
            safety check || true

      - sonarcloud/scan

      - run:
          name: Send Email Notification for SonarQube and Test Results
          command: |
            echo "Subject: CI/CD Pipeline Report for Devsec_A33" > email_body.txt
            echo "SonarQube analysis and test results are complete. Check the pipeline logs for details." >> email_body.txt
            echo "Test Results: $(tail -n 10 result.log)" >> email_body.txt
            echo "SonarQube Quality Gate: $(cat ~/.sonarcloud/qualitygate.json)" >> email_body.txt
            echo "View detailed logs: $(circleci build --job build)" >> email_body.txt
            cat email_body.txt | msmtp --from=default -t k213582@nu.edu.pk

  dockerize:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Docker image
          command: docker build -t $DOCKERHUB_USER/devsec_a33:latest .

      - run:
          name: Push Docker image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker push $DOCKERHUB_USER/devsec_a33:latest

workflows:
  version: 2
  main:
    jobs:
      - build:
          context: SonarCloud
      - dockerize:
          requires:
            - build
